<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Core" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Persistence" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Messaging" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Outbox" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Redis" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Resilience" />
    <PackageReference Include="SwiftBets.Contracts.Grpc" />
    <PackageReference Include="Grpc.Net.ClientFactory" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <ProjectReference Include="../SwiftBets.Placement.Application/SwiftBets.Placement.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Sql/*.sql" />
  </ItemGroup>
</Project>
